apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - args:
        env:
        - name: APP_URL
          value: http://localhost:5000
        - name: AUTHORITY
          value: localhost
        - name: BROKER_URL
          value: amqp://guest:guest@rabbit:5672//
        - name: CLIENT_URL
          value: http://localhost:3001/hypothesis
        - name: DATABASE_URL
          value: postgresql://postgres@postgres:5432/htest
        - name: ELASTICSEARCH_URL
          value: http://elasticsearch:9200
        - name: NEW_RELIC_APP_NAME
          value: h (prod)
        - name: NEW_RELIC_MONITOR_MODE
          value: "false"
        - name: SECRET_KEY
          value: notasecret
        image: hypothesis/hypothesis
        name: frontend
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
